server:
  port: 7213
spring:
  application:
    name: consumerservice

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: true
    fetch-registry: true
#    healthcheck:
#      enabled: true
  instance:
    # 此处建议写，不写默认是机器名
    prefer-ip-address: true
#    ip-address: 11.11.11.236
    # 优先级小于 application.properties ，如果你想知道当前注册上去的版本必须使用 application.properties 中的配置写法
    # 因为 bootstrap.yml 最早初始化，那时候还无法读取到 pom.xml 中的属性
    instance-id: localhost:${spring.application.name}:${server.port}
    # ip-address 强行指定此实例 IP ，不是很推荐，绝大多数情况 prefer-ip-address 与  preferred-networks 配合都够用了
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30


flag: dev-hk


feign:
  hystrix:
    enabled: true





